"""Add medical specialist resources to nova.json."""
import json
from pathlib import Path

NOVA_FILE = Path(__file__).parent.parent / "src" / "_data" / "resources" / "nova.json"

new_resources = [
    {"name": "Dr. Thanh Nguyen - Pediatric Neurology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Neurology at PSV. Medical Director of Neurology. Specializes in seizures, epilepsy, headaches, movement disorders, cerebral palsy, tics, and neuro-critical care.", "phone": "703-635-2873", "website": "https://psvcare.org/specialist/thanh-nguyen-md/", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["epilepsy", "cerebral-palsy"], "cost": "", "tags": ["pediatric", "neurology", "psv"], "source": "https://psvcare.org/specialist/thanh-nguyen-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. William McClintock - Pediatric Neurology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Neurology at PSV. Director of the Tuberous Sclerosis Clinic. Specializes in general child neurology, spasticity, headaches, and tuberous sclerosis.", "phone": "703-635-2873", "website": "https://psvcare.org/specialist/william-mcclintock-md/", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["tuberous-sclerosis", "spasticity"], "cost": "", "tags": ["pediatric", "neurology", "psv"], "source": "https://psvcare.org/specialist/william-mcclintock-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Tarannum Lateef - Pediatric Neurology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Neurology at PSV. Board-certified with MD from Northwestern University and MPH in Epidemiology from George Washington University.", "phone": "703-635-2873", "website": "https://psvcare.org/specialist/tarannum-lateef-md/", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["epilepsy"], "cost": "", "tags": ["pediatric", "neurology", "psv"], "source": "https://psvcare.org/specialist/tarannum-lateef-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Thuy-Anh Vu - Pediatric Neurology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Neurology at PSV. Board-certified pediatric neurologist specializing in epilepsy and general child neurology.", "phone": "703-635-2873", "website": "https://psvcare.org/specialist/thuy-anh-vu-md/", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["epilepsy"], "cost": "", "tags": ["pediatric", "neurology", "psv"], "source": "https://psvcare.org/specialist/thuy-anh-vu-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Patricia Seo-Mayer - Pediatric Nephrology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Nephrology at PSV. Medical Director of Nephrology & Hypertension. Specializes in acute kidney injury, chronic kidney disease, congenital anomalies, nephrotic syndrome, and hypertension.", "phone": "703-876-2788", "website": "https://psvcare.org/physicians/patricia-seo-mayer-md", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["kidney-disease"], "cost": "", "tags": ["pediatric", "nephrology", "psv"], "source": "https://psvcare.org/physicians/patricia-seo-mayer-md", "lastScraped": "2026-03-07"},
    {"name": "Dr. Rasheda Amin - Pediatric Nephrology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Nephrology at PSV. Fellowship trained at Children's National/George Washington University.", "phone": "703-876-2788", "website": "https://psvcare.org/physicians/rasheda-amin-md", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["kidney-disease"], "cost": "", "tags": ["pediatric", "nephrology", "psv"], "source": "https://psvcare.org/physicians/rasheda-amin-md", "lastScraped": "2026-03-07"},
    {"name": "Dr. Jacquelyn Calbert - Developmental Pediatrics", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Developmental Pediatrics at PSV. Medical Director of Neurodevelopmental Pediatrics. Kennedy Krieger/Johns Hopkins trained. Specializes in ADHD, autism, learning disabilities, and developmental delays.", "phone": "703-876-2788", "website": "https://psvcare.org/find-a-specialist-results?field_specialty_nid=401", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["autism", "adhd", "learning-disabilities", "developmental-delays"], "cost": "", "tags": ["pediatric", "developmental-pediatrics", "psv", "autism", "adhd"], "source": "https://psvcare.org/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Laurel Blakemore - Pediatric Orthopedics", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Orthopedics at PSV. CEO of PSV and board-certified pediatric orthopaedic surgeon. Past President of the Scoliosis Research Society. Specializes in scoliosis and complex spinal deformity.", "phone": "703-876-2788", "website": "https://psvcare.org/specialist/laurel-blakemore-md/", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["scoliosis", "spinal-deformity"], "cost": "", "tags": ["pediatric", "orthopedics", "psv", "scoliosis"], "source": "https://psvcare.org/specialist/laurel-blakemore-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Emily Hattwick - Pediatric Orthopedics", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Orthopedics at PSV. Medical Director of Orthopaedic Surgery & Sports Medicine. Specializes in pediatric hand surgery, congenital conditions, and post-traumatic deformities.", "phone": "703-876-2788", "website": "https://psvcare.org/physicians/emily-hattwick-md", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["congenital-hand-conditions", "limb-deformities"], "cost": "", "tags": ["pediatric", "orthopedics", "psv", "hand-surgery"], "source": "https://psvcare.org/physicians/emily-hattwick-md", "lastScraped": "2026-03-07"},
    {"name": "Dr. Kinjal Parikh - Pediatric Cardiology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Cardiology at Inova Children's. Board-certified pediatric and fetal cardiologist specializing in noninvasive imaging, echocardiography, and pulmonary hypertension.", "phone": "703-573-0504", "website": "https://www.inova.org/doctors/kinjal-parikh-md", "address": "8260 Willow Oaks Corporate Dr, Suite 400, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["congenital-heart-disease", "pulmonary-hypertension"], "cost": "", "tags": ["pediatric", "cardiology", "inova-childrens"], "source": "https://www.inova.org/doctors/kinjal-parikh-md", "lastScraped": "2026-03-07"},
    {"name": "Dr. Jason Goldberg - Pediatric Cardiology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Cardiology at Inova Children's. Director of Research and Director of Pediatric Heart Failure. Board certified in pediatric cardiology.", "phone": "703-573-0504", "website": "https://www.inova.org/doctors/jason-f-goldberg-md", "address": "8260 Willow Oaks Corporate Dr, Suite 400, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["heart-failure", "congenital-heart-disease"], "cost": "", "tags": ["pediatric", "cardiology", "inova-childrens"], "source": "https://www.inova.org/doctors/jason-f-goldberg-md", "lastScraped": "2026-03-07"},
    {"name": "Dr. Jin Hyuk Park - Pediatric Cardiology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Cardiology at Children's National Hospital (Northern Virginia). Over 20 years of experience as a pediatric cardiologist in Northern Virginia.", "phone": "571-226-8380", "website": "https://appointments.childrensnational.org/provider/jin-hyuk-park/2359687", "address": "3023 Hamaker Court, Suite 300, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["congenital-heart-disease"], "cost": "", "tags": ["pediatric", "cardiology", "childrens-national"], "source": "https://appointments.childrensnational.org/provider/jin-hyuk-park/2359687", "lastScraped": "2026-03-07"},
    {"name": "Dr. Mitchell Cohen - Pediatric Cardiology", "category": ["medical"], "location": "Northern Virginia", "area": "falls church", "description": "Pediatric Cardiology at Inova Children's Heart Center. Co-Director of the Heart Center at Inova L.J. Murphy Children's Hospital.", "phone": "703-573-0504", "website": "https://www.inovachildrens.org/services/heart/team", "address": "3300 Gallows Rd, Falls Church, VA 22042", "ageRange": "Pediatric", "disabilityTypes": ["congenital-heart-disease"], "cost": "", "tags": ["pediatric", "cardiology", "inova-childrens"], "source": "https://www.inovachildrens.org/services/heart/team", "lastScraped": "2026-03-07"},
    {"name": "Dr. Catherine Chao - Pediatric Gastroenterology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Gastroenterology at PSV. Fellowship trained at UCLA. Recipient of the Bronze Iams Quality Leadership Award for work with the Pediatric Feeding Team.", "phone": "703-635-7324", "website": "https://psvcare.org/specialist/catherine-chao-md/", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["digestive-disorders", "feeding-difficulties"], "cost": "", "tags": ["pediatric", "gastroenterology", "psv", "feeding-disorders"], "source": "https://psvcare.org/specialist/catherine-chao-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Grace Felix - Pediatric Gastroenterology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Gastroenterology at PSV. Specializes in digestive and liver disorders in infants, children, and adolescents. Washingtonian Top Doctor.", "phone": "703-635-7324", "website": "https://psvcare.org/physicians/grace-felix-md", "address": "3023 Hamaker Court, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["digestive-disorders", "liver-disorders"], "cost": "", "tags": ["pediatric", "gastroenterology", "psv"], "source": "https://psvcare.org/physicians/grace-felix-md", "lastScraped": "2026-03-07"},
    {"name": "Dr. Ian Leibowitz - Pediatric Gastroenterology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Gastroenterology at Children's National. Division Chief of GI, Hepatology and Nutrition. Expert in inflammatory bowel disease, GERD, and celiac disease.", "phone": "571-226-8380", "website": "https://appointments.childrensnational.org/provider/ian-h-leibowitz/2359892", "address": "3023 Hamaker Court, Suite 300, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["inflammatory-bowel-disease", "celiac-disease"], "cost": "", "tags": ["pediatric", "gastroenterology", "childrens-national"], "source": "https://appointments.childrensnational.org/provider/ian-h-leibowitz/2359892", "lastScraped": "2026-03-07"},
    {"name": "Dr. Dinesh Pillai - Pediatric Pulmonology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Pulmonology at PSV. Medical Director of Pulmonary Medicine. Developed the Severe Asthma Program and Aerodigestive Program. Specializes in severe asthma, aerodigestive diseases, and rare lung conditions.", "phone": "703-635-2768", "website": "https://psvcare.org/specialist/dinesh-pillai-md/", "address": "3023 Hamaker Court, Suite 300, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["severe-asthma", "chronic-lung-disease"], "cost": "", "tags": ["pediatric", "pulmonology", "psv"], "source": "https://psvcare.org/specialist/dinesh-pillai-md/", "lastScraped": "2026-03-07"},
    {"name": "Dr. Dagne Assefa - Pediatric Pulmonology", "category": ["medical"], "location": "Northern Virginia", "area": "fairfax", "description": "Pediatric Pulmonology at PSV. Board-certified (FAAP, FCCP). Fluent in English, Amharic, and German.", "phone": "703-635-2768", "website": "https://psvcare.org/specialist/dagne-assefa-md-faap-fccp/", "address": "3023 Hamaker Court, Suite 300, Fairfax, VA 22031", "ageRange": "Pediatric", "disabilityTypes": ["asthma", "chronic-lung-disease"], "cost": "", "tags": ["pediatric", "pulmonology", "psv"], "source": "https://psvcare.org/specialist/dagne-assefa-md-faap-fccp/", "lastScraped": "2026-03-07"}
]

with open(NOVA_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

existing_names = {r["name"].lower() for r in data}
added = 0
for r in new_resources:
    if r["name"].lower() not in existing_names:
        data.append(r)
        added += 1
    else:
        print(f"Skipped duplicate: {r['name']}")

with open(NOVA_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Added {added} medical specialists. Total: {len(data)}")
