"""Add sensory-friendly venue resources to nova.json."""
import json
from pathlib import Path

NOVA_FILE = Path(__file__).parent.parent / "src" / "_data" / "resources" / "nova.json"

new_resources = [
    {"name": "Smithsonian Morning at the Museum (Sensory-Friendly)", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "washington, dc", "description": "Free sensory-friendly program where pre-registered families visit a Smithsonian museum before it opens. Includes social narratives, sensory maps, visual schedules, and calming spaces.", "phone": "", "website": "https://access.si.edu/program/morning-museum", "address": "", "ageRange": "Children, teens, and young adults", "disabilityTypes": [], "cost": "Free", "tags": ["sensory-friendly", "museums", "free"], "source": "https://access.si.edu/program/morning-museum", "lastScraped": "2026-03-07"},
    {"name": "National Children's Museum - Sensory-Friendly Hours", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "washington, dc", "description": "Sensory-friendly hours with adjusted lighting and sound. Free sensory backpacks with noise-reduction headphones and fidgets available at admission desk.", "phone": "(202) 844-2486", "website": "https://nationalchildrensmuseum.org/explore/programs/sensory-friendly-hours", "address": "1300 Pennsylvania Ave NW, Washington, DC 20004", "ageRange": "", "disabilityTypes": [], "cost": "", "tags": ["sensory-friendly", "children", "museum", "sensory-bags"], "source": "https://nationalchildrensmuseum.org/explore/programs/sensory-friendly-hours", "lastScraped": "2026-03-07"},
    {"name": "National Air and Space Museum - Udvar-Hazy Center (Sensory Resources)", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "chantilly", "description": "Sensory bags with noise-reduction headphones and fidgets available at Welcome Center. Social narratives provided for visit preparation. Free admission.", "phone": "(703) 572-4118", "website": "https://airandspace.si.edu/visit/udvar-hazy-center/accessibility", "address": "14390 Air and Space Museum Pkwy, Chantilly, VA 20151", "ageRange": "", "disabilityTypes": [], "cost": "Free admission; parking fee applies", "tags": ["sensory-friendly", "museum", "sensory-bags", "free"], "source": "https://airandspace.si.edu/visit/udvar-hazy-center/accessibility", "lastScraped": "2026-03-07"},
    {"name": "Smithsonian's National Zoo - Sensory-Friendly Resources", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "washington, dc", "description": "Downloadable social narratives, tactile elements throughout the zoo, and Aira Access app for verbal descriptions and wayfinding. Free admission.", "phone": "(202) 633-4888", "website": "https://nationalzoo.si.edu/visit/accessibility-and-sensory-information", "address": "3001 Connecticut Ave NW, Washington, DC 20008", "ageRange": "", "disabilityTypes": [], "cost": "Free", "tags": ["sensory-friendly", "zoo", "social-narratives", "outdoors", "free"], "source": "https://nationalzoo.si.edu/visit/accessibility-and-sensory-information", "lastScraped": "2026-03-07"},
    {"name": "George Washington's Mount Vernon - Sensory-Friendly Family Morning", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "alexandria", "description": "Early morning access (8-9 AM) for neurodivergent families before general opening. Sensory bags, quiet room, and hands-on Mansion tours with pre-visit social narratives.", "phone": "(703) 780-2000", "website": "https://www.mountvernon.org/plan-your-visit/calendar/events/sensory-friendly-family-morning", "address": "3200 Mount Vernon Memorial Highway, Mount Vernon, VA 22121", "ageRange": "", "disabilityTypes": [], "cost": "$11 adults/youth; free under 5", "tags": ["sensory-friendly", "historic-site", "sensory-bags", "social-narratives"], "source": "https://www.mountvernon.org/plan-your-visit/calendar/events/sensory-friendly-family-morning", "lastScraped": "2026-03-07"},
    {"name": "Kennedy Center - Sensory-Friendly Performances", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "washington, dc", "description": "Performances with reduced sound, dimmed lights, limited strobe effects, designated quiet areas, and freedom to move during shows. Pre-visit social stories and activity books provided.", "phone": "(202) 416-8727", "website": "https://www.kennedy-center.org/visit/accessibility/sensory/", "address": "2700 F St NW, Washington, DC 20566", "ageRange": "", "disabilityTypes": [], "cost": "Varies by performance", "tags": ["sensory-friendly", "performing-arts", "theater", "music"], "source": "https://www.kennedy-center.org/visit/accessibility/sensory/", "lastScraped": "2026-03-07"},
    {"name": "LEGO Discovery Center - Sensory-Friendly Mornings", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "springfield", "description": "First Wednesday of each month at 10 AM with reduced lighting and music. KultureCity certified as sensory inclusive with trained staff.", "phone": "(571) 506-4322", "website": "https://www.legolanddiscoverycenter.com/", "address": "6563 Springfield Mall, Suite 12004, Springfield, VA 22150", "ageRange": "Ages 2-12", "disabilityTypes": [], "cost": "Admission required", "tags": ["sensory-friendly", "indoor-play", "KultureCity-certified"], "source": "https://www.legolanddiscoverycenter.com/", "lastScraped": "2026-03-07"},
    {"name": "We Rock the Spectrum - Loudoun", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "ashburn", "description": "Indoor sensory play gym for all ability levels with zip line, trampoline, swings, climbing structure, arts and crafts, and a dedicated calming room.", "phone": "(571) 479-8567", "website": "https://werockthespectrumloudounva.com/", "address": "21720 Red Rum Dr, Suites 177-182, Ashburn, VA 20147", "ageRange": "", "disabilityTypes": [], "cost": "", "tags": ["sensory-friendly", "indoor-play", "sensory-gym", "calming-room"], "source": "https://werockthespectrumloudounva.com/", "lastScraped": "2026-03-07"},
    {"name": "AMC Tysons Corner 16 - Sensory Friendly Films", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "mclean", "description": "Sensory Friendly Films with Autism Society on 2nd/4th Saturday (family) and Wednesday evenings (mature). Lights up, sound down, audience free to move and talk.", "phone": "", "website": "https://www.amctheatres.com/programs/sensory-friendly-films", "address": "1961 Chain Bridge Rd, McLean, VA 22102", "ageRange": "", "disabilityTypes": [], "cost": "Standard ticket price", "tags": ["sensory-friendly", "movies", "autism-society-partner"], "source": "https://www.amctheatres.com/programs/sensory-friendly-films", "lastScraped": "2026-03-07"},
    {"name": "Alamo Drafthouse One Loudoun - Sensory-Friendly Screenings", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "ashburn", "description": "Weekly 'Alamo For All' sensory-friendly screenings every Tuesday before 2:05 PM. Brighter lights, lower sound, no previews, and movement welcomed.", "phone": "(571) 293-6808", "website": "https://drafthouse.com/program/alamo-for-all", "address": "20575 Easthampton Plaza, Ashburn, VA 20147", "ageRange": "All ages", "disabilityTypes": [], "cost": "Standard ticket price", "tags": ["sensory-friendly", "movies", "weekly-program"], "source": "https://drafthouse.com/program/alamo-for-all", "lastScraped": "2026-03-07"},
    {"name": "Alamo Drafthouse Woodbridge - Sensory-Friendly Screenings", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "woodbridge", "description": "Weekly 'Alamo For All' sensory-friendly screenings every Tuesday before 2:05 PM. Brighter lights, lower sound, no previews, and movement welcomed.", "phone": "(571) 260-4413", "website": "https://drafthouse.com/program/alamo-for-all", "address": "15200 Potomac Town Place, Suite 100, Woodbridge, VA 22191", "ageRange": "All ages", "disabilityTypes": [], "cost": "Standard ticket price", "tags": ["sensory-friendly", "movies", "weekly-program"], "source": "https://drafthouse.com/program/alamo-for-all", "lastScraped": "2026-03-07"},
    {"name": "Colvin Run Mill - Sensory-Friendly Events", "category": ["recreation", "sensory"], "location": "Northern Virginia", "area": "great falls", "description": "Fairfax County historic gristmill offering seasonal sensory-friendly events in a quiet environment including sensory-friendly Santa visits and holiday crafts.", "phone": "", "website": "https://www.fairfaxcounty.gov/parks/colvinrunmill/", "address": "10017 Colvin Run Road, Great Falls, VA 22066", "ageRange": "", "disabilityTypes": [], "cost": "Varies by event", "tags": ["sensory-friendly", "historic-site", "seasonal-events", "outdoors"], "source": "https://www.fairfaxcounty.gov/parks/colvinrunmill/", "lastScraped": "2026-03-07"}
]

with open(NOVA_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

existing_names = {r["name"].lower() for r in data}
added = 0
for r in new_resources:
    if r["name"].lower() not in existing_names:
        data.append(r)
        added += 1
    else:
        print(f"Skipped duplicate: {r['name']}")

with open(NOVA_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Added {added} sensory-friendly venues. Total: {len(data)}")
