"""Add therapy providers to nova.json"""
import json
from pathlib import Path

NOVA_FILE = Path(__file__).parent.parent / "src" / "_data" / "resources" / "nova.json"

new_providers = [
  {
    "name": "Inova Fairfax Outpatient Pediatric Rehabilitation",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "Hospital-based pediatric rehabilitation offering occupational therapy, physical therapy, and speech therapy through Inova Children's Hospital. Specializes in feeding and swallowing disorders.",
    "phone": "703-776-6080",
    "website": "https://www.inova.org/locations/inova-fairfax-outpatient-pediatric-rehabilitation",
    "address": "8260 Willow Oaks Corporate Dr, Suite 450, Fairfax, VA 22031",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "feeding-therapy", "hospital-based"],
    "source": "https://www.inova.org/locations/inova-fairfax-outpatient-pediatric-rehabilitation",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Inova Loudoun Hospital Pediatric Rehabilitation",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "leesburg",
    "description": "Hospital-based pediatric rehabilitation offering OT, PT, and speech therapy for infants through adolescents with parent education and involvement.",
    "phone": "703-858-6667",
    "website": "https://www.inovachildrens.org/rehabilitation/ilh",
    "address": "44035 Riverside Parkway, Suite 500, Leesburg, VA 20176",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "hospital-based"],
    "source": "https://www.inovachildrens.org/rehabilitation/ilh",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Children's National Hospital - Northern Virginia",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "Outpatient specialty care location of Children's National Hospital offering pediatric specialty services including rehabilitation and therapy.",
    "phone": "301-572-3542",
    "website": "https://www.childrensnational.org/get-care/locations/northern-virginia",
    "address": "3023 Hamaker Court, Suite 300, Fairfax, VA 22031",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["pediatric-specialists", "hospital-based", "multi-specialty"],
    "source": "https://www.childrensnational.org/get-care/locations/northern-virginia",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "VHC Health Outpatient Rehabilitation",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "arlington",
    "description": "Outpatient rehabilitation at Virginia Hospital Center offering physical therapy, occupational therapy, and speech-language therapy for patients of all ages.",
    "phone": "703-558-6507",
    "website": "https://www.vhchealth.org/medical-services/rehabilitation/",
    "address": "1851 N. George Mason Drive, Ground Floor, Arlington, VA 22207",
    "ageRange": "All ages",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "hospital-based"],
    "source": "https://www.vhchealth.org/medical-services/rehabilitation/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Sentara Northern Virginia - Pediatric Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "woodbridge",
    "description": "Pediatric therapy program offering individualized OT, PT, and speech therapy for autism, cerebral palsy, cognitive impairment, and sensory integration.",
    "phone": "",
    "website": "https://www.sentara.com/medicalservices/rehabilitation-and-therapy/specialty-therapy-services/pediatric-therapy",
    "address": "",
    "ageRange": "Pediatric",
    "disabilityTypes": ["autism", "cerebral-palsy"],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "hospital-based"],
    "source": "https://www.sentara.com/medicalservices/rehabilitation-and-therapy/specialty-therapy-services/pediatric-therapy",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Skills on the Hill",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "arlington",
    "description": "Pediatric therapy practice offering occupational, physical, and speech-language therapy for children from birth through teens across home, community, and school settings.",
    "phone": "",
    "website": "https://skillsonthehill.com/",
    "address": "2301 Columbia Pike, #125a, Arlington, VA 22204",
    "ageRange": "Pediatric (birth through teens)",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy"],
    "source": "https://skillsonthehill.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Progressive Pediatric Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "falls church",
    "description": "One-on-one physical, occupational, speech, and art therapy for infants through school-age children. Also offers hippotherapy and aquatic therapy.",
    "phone": "703-606-6213",
    "website": "https://www.progressivepediatrics.net/",
    "address": "150 South Washington Street, Suite 203, Falls Church, VA 22046",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "art-therapy", "hippotherapy", "aquatic-therapy"],
    "source": "https://www.progressivepediatrics.net/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Premier Pediatric Therapy Source",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "annandale",
    "description": "Therapist-owned practice providing occupational, physical, speech, and nutrition therapy in clinic, home, community, and telehealth.",
    "phone": "703-879-2479",
    "website": "https://premierpedstherapy.com/",
    "address": "6715 Little River Turnpike, Suite 200, Annandale, VA 22003",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "nutrition", "telehealth", "in-home"],
    "source": "https://premierpedstherapy.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Little Hands Pediatric Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "ashburn",
    "description": "Speech, occupational, physical, and feeding therapy in clinic, at home, school, or daycare throughout Loudoun and western Fairfax counties.",
    "phone": "571-207-8850",
    "website": "https://littlehandspediatrictherapy.com/",
    "address": "42395 Ryan Rd, Suite 112, Ashburn, VA 20148",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "speech-therapy", "feeding-therapy", "in-home"],
    "source": "https://littlehandspediatrictherapy.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Good Beginnings Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "Over 30 years of comprehensive occupational and physical therapy for children addressing fine/gross motor skills, sensory processing, self-care, and self-regulation.",
    "phone": "703-536-1817",
    "website": "https://gbtherapy.org/",
    "address": "",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "Accepts many insurances; does not accept Medicaid",
    "tags": ["occupational-therapy", "physical-therapy", "sensory-processing"],
    "source": "https://gbtherapy.org/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Pediatric Therapy Specialists (NOVA Ped Therapy)",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "Motor and sensory-based occupational and physical therapy for developmental delays, sensory processing, ASD, and ADHD.",
    "phone": "703-503-5300",
    "website": "https://novapedtherapy.com/",
    "address": "9673 Main Street, Suite A, Fairfax, VA 22031",
    "ageRange": "Pediatric",
    "disabilityTypes": ["autism", "adhd", "developmental-delays"],
    "cost": "",
    "tags": ["occupational-therapy", "physical-therapy", "sensory-processing"],
    "source": "https://novapedtherapy.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Fairfax Pediatric Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "Occupational therapy, speech therapy, music therapy, and adapted yoga classes with in-clinic, in-home, and teletherapy options.",
    "phone": "571-587-6244",
    "website": "https://fairfaxpediatrictherapy.com/",
    "address": "3975 University Drive, Suite 450, Fairfax, VA 22030",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "speech-therapy", "music-therapy", "yoga", "telehealth"],
    "source": "https://fairfaxpediatrictherapy.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "FUNdamentals and Building Blocks Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "falls church",
    "description": "Pediatric speech, language, and occupational therapy practice serving Northern Virginia and Washington, DC since 2016.",
    "phone": "703-533-8819",
    "website": "https://buildingblockstherapy.com/",
    "address": "450 W Broad St, Suite 215, Falls Church, VA 22046",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "speech-therapy"],
    "source": "https://buildingblockstherapy.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Playworks Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "arlington",
    "description": "Pediatric occupational therapy and speech-language therapy for children up to 16 years with clinical and virtual sessions.",
    "phone": "703-243-4600",
    "website": "https://www.playworksspeech.com/",
    "address": "4620 Lee Hwy, Suite 215, Arlington, VA 22207",
    "ageRange": "Pediatric (up to 16)",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["occupational-therapy", "speech-therapy", "telehealth"],
    "source": "https://www.playworksspeech.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Pediatric Therapy Studio",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "ABA therapy, speech therapy, and occupational therapy for children with autism, speech delays, and developmental challenges.",
    "phone": "",
    "website": "https://www.pediatrictherapystudio.com/",
    "address": "",
    "ageRange": "Pediatric",
    "disabilityTypes": ["autism", "speech-delays", "developmental-delays"],
    "cost": "Accepts insurance",
    "tags": ["aba-therapy", "speech-therapy", "occupational-therapy", "autism"],
    "source": "https://www.pediatrictherapystudio.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "TLC Occupational Therapy",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "purcellville",
    "description": "Pediatric occupational therapy for sensory processing disorders, food texture aversions, autism, Down syndrome, and developmental delays.",
    "phone": "703-239-3365",
    "website": "https://www.tlcotllc.com/",
    "address": "205 E Hirst Rd, Suite 205, Purcellville, VA 20132",
    "ageRange": "Pediatric",
    "disabilityTypes": ["autism", "down-syndrome", "sensory-processing"],
    "cost": "",
    "tags": ["occupational-therapy", "sensory-processing"],
    "source": "https://www.tlcotllc.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "The Speech and Language Center",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "sterling",
    "description": "Speech therapy, occupational therapy, and behavioral therapy in Loudoun County for children with communication, developmental, and behavioral needs.",
    "phone": "",
    "website": "https://speechandlanguagecenter.com/",
    "address": "",
    "ageRange": "Pediatric",
    "disabilityTypes": [],
    "cost": "",
    "tags": ["speech-therapy", "occupational-therapy", "behavioral-therapy"],
    "source": "https://speechandlanguagecenter.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Achieve Beyond Pediatric Therapy & Autism Services",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "Multi-disciplinary clinic offering speech, physical, occupational, and clinic-based ABA therapy for children from birth to age 21.",
    "phone": "703-237-2219",
    "website": "https://www.achievebeyondusa.com/locations/virginia/",
    "address": "11200 Waples Mill Rd, Suite 100, Fairfax, VA 22030",
    "ageRange": "Birth to 21",
    "disabilityTypes": ["autism"],
    "cost": "Accepts private insurance",
    "tags": ["aba-therapy", "speech-therapy", "occupational-therapy", "physical-therapy", "autism"],
    "source": "https://www.achievebeyondusa.com/locations/virginia/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Infinity ABA Therapy & Autism Services",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "fairfax",
    "description": "ABA therapy for children with autism and ADHD. Programs include 1:1 in-home therapy, Early Learners Social Club, and full-day preschool.",
    "phone": "571-241-8557",
    "website": "https://www.infinityaba.com/",
    "address": "11211 Waples Mill Rd, Fairfax, VA 22030",
    "ageRange": "Pediatric (18 months and up)",
    "disabilityTypes": ["autism", "adhd"],
    "cost": "",
    "tags": ["aba-therapy", "autism", "social-skills", "preschool"],
    "source": "https://www.infinityaba.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Patterson Behavior Services",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "arlington",
    "description": "In-home ABA therapy for young children by a doctoral-level BCBA-D. Serves Arlington, Alexandria, Falls Church, and Fairfax.",
    "phone": "571-317-1044",
    "website": "https://www.pattersonbehavior.com/",
    "address": "4342 4th St N, Arlington, VA 22203",
    "ageRange": "Pediatric (1-21)",
    "disabilityTypes": ["autism", "developmental-disabilities"],
    "cost": "",
    "tags": ["aba-therapy", "autism", "in-home"],
    "source": "https://www.pattersonbehavior.com/",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "Proud Moments ABA - Alexandria",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "alexandria",
    "description": "Evidence-based ABA therapy for Autism Spectrum Disorder with tailored treatment plans, behavior intervention, and parent engagement support.",
    "phone": "",
    "website": "https://www.proudmomentsaba.com/alexandria-va-aba-therapy",
    "address": "2560 Huntington Ave, Suite 104, Alexandria, VA 22303",
    "ageRange": "Pediatric",
    "disabilityTypes": ["autism"],
    "cost": "",
    "tags": ["aba-therapy", "autism", "in-home"],
    "source": "https://www.proudmomentsaba.com/alexandria-va-aba-therapy",
    "lastScraped": "2026-03-07"
  },
  {
    "name": "ABC Behavior",
    "category": ["therapy"],
    "location": "Northern Virginia",
    "area": "manassas",
    "description": "ABA therapy for individuals aged 1-21 with developmental disabilities across in-home, clinic, social group, and community settings.",
    "phone": "",
    "website": "https://abcbehavior.org/",
    "address": "",
    "ageRange": "Ages 1-21",
    "disabilityTypes": ["autism", "developmental-disabilities"],
    "cost": "",
    "tags": ["aba-therapy", "autism", "social-skills", "in-home"],
    "source": "https://abcbehavior.org/",
    "lastScraped": "2026-03-07"
  }
]

with open(NOVA_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

existing_names = {r["name"].lower() for r in data}
added = 0
for p in new_providers:
    if p["name"].lower() not in existing_names:
        data.append(p)
        added += 1
    else:
        print(f"Skipped duplicate: {p['name']}")

with open(NOVA_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Added {added} therapy providers. Total resources: {len(data)}")
